// <auto-generated />
namespace NETBootcamp.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix01));
        
        string IMigrationMetadata.Id
        {
            get { return "201807251104128_fix01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
